### ISSUE TITLE
[FR] Show pages

### ISSUE THREAD

**Issue by ildar** [andviane/google-books-android-viewer#1]
Is the app going to show pages of books?

**Comment by andviane** [comment]
The full content of the book is not available through the Google API used. Do you mean the preview page? There is s link in the API called "previewLink", but this would only be a small part of the book.

**Comment by ildar** [comment]
Yes, the preview page. If nothing but the "previewLink" is available, I
think adding this hyper-link is fine.  No need to view the preview in the
app IMHO.
Thanks.

**Comment by andviane** [comment]
This is not complex to do. Just implemented (v1.8), commit [1aaa1b1e2ceaf5f2c31489f67414dc9e751bb341](https://github.com/andviane/google-books-android-viewer/commit/1aaa1b1e2ceaf5f2c31489f67414dc9e751bb341)

**Comment by ildar** [comment]
Thanks!
What do you think about publishing the app in F-Droid.org ?

**Comment by andviane** [comment]
The app has the packaging request entry [here](https://gitlab.com/fdroid/rfp/issues/174). Let me known if something else should be done.
